/*
 * Ski Data API for NEU Seattle distributed systems course
 * An API for an emulation of skier managment system for RFID tagged lift tickets. Basis for CS6650 Assignments for 2019
 *
 * OpenAPI spec version: 1.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.LiftRide;
import io.swagger.client.model.ResponseMsg;
import io.swagger.client.model.SkierVertical;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SkiersApi
 */
@Ignore
public class SkiersApiTest {

    private final SkiersApi api = new SkiersApi();

    /**
     * 
     *
     * get the total vertical for the skier for the specified ski day
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSkierDayVerticalTest() throws ApiException {
        String resortID = null;
        String dayID = null;
        String skierID = null;
        SkierVertical response = api.getSkierDayVertical(resortID, dayID, skierID);

        // TODO: test validations
    }
    /**
     * get the total vertical for the skier for the specified resort
     *
     * get the total vertical for the skier the specified resort.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSkierResortTotalsTest() throws ApiException {
        String skierID = null;
        List<String> resort = null;
        SkierVertical response = api.getSkierResortTotals(skierID, resort);

        // TODO: test validations
    }
    /**
     * write a new lift ride for the skier
     *
     * Stores new lift ride details in the data store
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void writeNewLiftRideTest() throws ApiException {
        LiftRide body = null;
        api.writeNewLiftRide(body);

        // TODO: test validations
    }
}
